apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config.yaml
  - task/clusterloader2/loadtest/0.1/runload.yaml
  - task/clusterloader2/loadtest/0.1/tests/run.yaml
  - task/clusterloader2/loadtest/0.1/secret.yaml
  - task/eks-cluster-create/eksctl/0.1/create-eks-cluster.yaml
  - task/eks-cluster-create/eksctl/0.1/tests/run.yaml
  - task/eks-cluster-teardown/eksctl/0.1/teardown-eks-cluster.yaml
  - task/eks-cluster-teardown/eksctl/0.1/tests/teardown-eks-cluster.yaml
  - task/eks-cluster-teardown/eksctl/0.1/tests/secret.yaml  
  - task/eks-cluster-teardown/eksctl/0.1/tests/teardown-eks-cluster.yaml
  - task/vertical-autoscaling/mig/0.1/load-10-medium-medium.yaml
  - task/vertical-autoscaling/up/0.1/loadtest.yaml
  - pipeline/eks-cl2/eksctl/0.1/eks-cl2.yaml
  - pipeline/eks-cl2/eksctl/0.1/tests/cronjob.yaml
  - pipeline/eks-cl2/eksctl/0.1/tests/eventlistener.yaml
  - pipeline/eks-cl2/eksctl/0.1/tests/triggerbinding.yaml
  - pipeline/eks-cl2/eksctl/0.1/tests/triggertemplate.yaml
  - pipeline/eks-cl2/eksctl/0.1/tests/run.yaml
  - pipeline/eks-vas-mig/akt/0.1/eks-vas-mig.yaml
  - pipeline/eks-vas-mig/akt/0.1/tests/cronjob.yaml
  - pipeline/eks-vas-mig/akt/0.1/tests/eventlistener.yaml
  - pipeline/eks-vas-mig/akt/0.1/tests/triggerbinding.yaml
  - pipeline/eks-vas-mig/akt/0.1/tests/triggertemplate.yaml
  - pipeline/eks-vas-mig/akt/0.1/tests/pipelinerun.yaml
