---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: runloadtest
  namespace: hakuna
spec:
  params:
  - name: message
    description: The message to print
    default: "finished running load test"
    type: string
  steps:
  - name: cl2test
    image: bash
    command: ["bash", "-c"]
    args:
      - echo '$(params.message)'
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: delete-cluster
  namespace: hakuna
spec:
  steps:
  - name: bye-cluster
    image: bash
    command: ["bash", "-c"]
    args:
    - echo 'Goodbye Cluster!'
---      
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: vas-mig
  namespace: hakuna
spec:
  params:
  - name: message
    description: The message to print
    default: This is the default message
    type: string
  tasks:
  - name: create-eks-cluster
    taskRef:
      name: vas-cl2-mig
  - name: runloadtest
    runAfter: [create-eks-cluster]
    taskRef:
      name: runloadtest
    params:
    - name: message
      value: $(params.message)
  - name: deletecluster
    runAfter: [runloadtest]
    taskRef:
      name: deletecluster