---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./k8s-config/addons/metrics-server
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system0
  validation: client