---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: test-workflow
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./k8s-config/test-workflows/eks
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system0
  validation: client
